name: Use App token
description: Run a GitHub Action as a GitHub App to use the app's token.
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  app_id:
    description: The ID of the GitHub App.
    required: true
  private_key:
    description: The private key of the GitHub App (can be Base64 encoded).
    required: true
  variable_name:
    description: The name of generated token in output and exported variable.
    required: false
    default: token
  secret_name:
    description: The secret name created on current repository.
    required: false
  clean_secret:
    description: Shoule clean the secret or not when completed.
    required: false
    default: false

outputs:
  token:
    description: An installation token for the GitHub App on the current repository.

runs:
  using: node12
  main: dist/index.js
  post: dist/index.js

branding:
  icon: anchor
  color: orange # gray-dark purple red orange green blue yellow black white
