name: Needs More Info
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🚧　Install
        run: |
          yarn
      - name: 📦　Build
        run: |
          yarn build
      - name: 🔑　Generate token
        id: generate_token
        uses: ./
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: bubkoo/needs-more-info@v1
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          CONFIG_FILE: .github/needs-more-info.yml
